### PR TITLE
Fixed python 3.X compatibility problem.

### PR DESCRIPTION
**Pull request by yurivict**
Originally submitted: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=201346

### CODE REVIEW

**Comment by njsmith** [comment]
Thanks!

**Comment by yurivict** [comment]
@njsmith Could you maybe make a release? It has been a while since the last release. Now python3 becomes more and more popular, better have the project compatible.

Thanks!

**Comment by njsmith** [comment]
I agree, lack of python 3 support is embarrassing, i just have tons of
things on my plate and don't even use this library since like 5 years
ago... Any chance you'd be interested in making that release? :-)

**Comment by yurivict** [comment]
I also don't use it. I happen to be the maintainer of the package in FreeBSD, and somebody asked about py3 support.

**Pull request merged**
